version: '3'

services:
  fhq2015_nodejs_jedi:
    image: freehackquest/angular-cli-start:latest
    environment:
      - NODE_ENV=production
      - 
    restart: always
    volumes:
      - "./others:/home/node"
      - "./tmp/.npm/:/root/.npm/"
      - "./tmp/node_modules/:/home/node/node_modules"
    restart: always
    command: "bash -c './start.sh'"
    ports:
      - "5000:5000"
    networks:
      - fhq2015_nodejs_jedi_net

networks:
  fhq2015_nodejs_jedi_net:
    driver: bridge